services:
  omega:
    image: ghcr.io/if6was9/omega
    environment:
      GIT_URL: https://github.com/if6was9/omega
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.ssh:/root/.ssh
    pull_policy: never
    restart: no
